export const demoProducts = [
  {
    id: "demo-core-360",
    slug: "core-360-camp-light",
    category: "کمپ",
    name: "چراغ کمپ Core 360",
    subtitle: "نور ماژولار فضای باز",
    description: "چراغ جمع‌وجور برای کمپ و استفاده روزمره با نور ۳۶۰ درجه و طراحی مناسب حمل.",
    price: 2490000,
    compare_at_price: 2790000,
    stock: 18,
    badge: "پیشنهاد JAST",
    type: "lamp",
    image_url: null,
    active: true,
  },
  {
    id: "demo-field-20k",
    slug: "field-20k-power-bank",
    category: "تکنولوژی",
    name: "پاوربانک Field 20K",
    subtitle: "USB-C PD / Outdoor",
    description: "پاوربانک ظرفیت بالا برای سفر و مسیرهای چندروزه با خروجی USB-C PD.",
    price: 3190000,
    compare_at_price: null,
    stock: 12,
    badge: "پرفروش",
    type: "power",
    image_url: null,
    active: true,
  },
  {
    id: "demo-ride-11",
    slug: "ride-11-repair-kit",
    category: "دوچرخه",
    name: "کیت تعمیر Ride 11",
    subtitle: "کیت جمع‌وجور مسیر",
    description: "یازده ابزار ضروری در یک فرم فشرده برای تعمیرات سریع دوچرخه در مسیر.",
    price: 1590000,
    compare_at_price: 1750000,
    stock: 25,
    badge: "ضروری",
    type: "tool",
    image_url: null,
    active: true,
  },
  {
    id: "demo-move-22",
    slug: "move-22l-day-pack",
    category: "سفر",
    name: "کوله Move 22L",
    subtitle: "روزانه و سفر سبک",
    description: "کوله ۲۲ لیتری سبک برای رفت‌وآمد شهری، سفر یک‌روزه و طبیعت‌گردی سبک.",
    price: 4290000,
    compare_at_price: null,
    stock: 9,
    badge: "جدید",
    type: "pack",
    image_url: null,
    active: true,
  },
  {
    id: "demo-trail-filter",
    slug: "trail-water-filter",
    category: "طبیعت‌گردی",
    name: "فیلتر آب Trail",
    subtitle: "فشرده و سبک",
    description: "فیلتر سبک برای استفاده در برنامه‌های طبیعت‌گردی و سفرهای کوتاه.",
    price: 1890000,
    compare_at_price: 2090000,
    stock: 16,
    badge: "Field Ready",
    type: "bottle",
    image_url: null,
    active: true,
  },
  {
    id: "demo-solo-2p",
    slug: "solo-2p-tent",
    category: "کمپ",
    name: "چادر Solo 2P",
    subtitle: "دو نفره / سه فصل",
    description: "چادر دو نفره سه فصل برای کمپ سبک با تمرکز روی نصب سریع و حمل ساده.",
    price: 8990000,
    compare_at_price: 9490000,
    stock: 7,
    badge: "Drop 01",
    type: "tent",
    image_url: null,
    active: true,
  },
  {
    id: "demo-smart-rear",
    slug: "smart-ride-rear-light",
    category: "دوچرخه",
    name: "چراغ عقب Smart Ride",
    subtitle: "دید بالا / USB-C",
    description: "چراغ عقب شارژی برای افزایش دیده‌شدن در مسیرهای شهری و جاده‌ای.",
    price: 1390000,
    compare_at_price: null,
    stock: 21,
    badge: "هوشمند",
    type: "rear",
    image_url: null,
    active: true,
  },
  {
    id: "demo-gear-cube",
    slug: "gear-cube-organizer",
    category: "سفر",
    name: "ارگانایزر Gear Cube",
    subtitle: "کابل، پاور و ابزار",
    description: "ارگانایزر چندبخشی برای نگهداری کابل، شارژر، ابزار کوچک و لوازم سفر.",
    price: 1290000,
    compare_at_price: null,
    stock: 30,
    badge: "کاربردی",
    type: "case",
    image_url: null,
    active: true,
  },
];

export function formatPrice(value) {
  return `${new Intl.NumberFormat("fa-IR").format(Number(value || 0))} تومان`;
}

export function getDemoProduct(slug) {
  return demoProducts.find((product) => product.slug === slug) || null;
}
